using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class CalculUIManager : MonoBehaviour
{
    [Header("UI")]
    [SerializeField] private TMP_Text questionText; // calculation-value
    [SerializeField] private TMP_Text propositionsText; // proposition-value (single TMP to list 3 choices)
    [SerializeField] private TMP_Text progressText; // progress-value (ex: "1/3")
    [SerializeField] private Image successImage; // SucessImage
    [SerializeField] private Image failImage;    // FailImage

    private MiniGame_CalculManager calculManager;
    private CalculLogic.CalculationData currentCalculation;
    private bool awaitingAnswer;

    void Awake()
    {
        calculManager = FindObjectOfType<MiniGame_CalculManager>();
        
        if (successImage != null) successImage.enabled = false;
        if (failImage != null) failImage.enabled = false;
    }

    void Start()
    {
    }

    public void DisplayCalculation(CalculLogic.CalculationData data)
    {
        currentCalculation = data;
        if (questionText != null) questionText.text = data.Question;
        if (propositionsText != null)
        {
            var a0 = data.Answers.Count > 0 ? data.Answers[0].ToString() : "";
            var a1 = data.Answers.Count > 1 ? data.Answers[1].ToString() : "";
            var a2 = data.Answers.Count > 2 ? data.Answers[2].ToString() : "";
            propositionsText.text = $"1) {a0,-5}  2) {a1,-5}  3) {a2}";
        }
        UpdateProgressDisplay();
        if (successImage != null) successImage.enabled = false;
        if (failImage != null) failImage.enabled = false;
        awaitingAnswer = true;
    }

    private void UpdateProgressDisplay()
    {
        if (calculManager == null)
        {
            calculManager = FindObjectOfType<MiniGame_CalculManager>();
        }
        if (progressText != null && calculManager != null)
        {
            progressText.text = $"{calculManager.CorrectAnswers}/{calculManager.RequiredCorrectAnswers}";
        }
    }

    void Update()
    {
        // Gestion des boutons P1_B1 / P1_B2 / P1_B3
        if (Input.GetButtonDown("P1_B1") || Input.GetKeyDown(KeyCode.F))
        {
            CheckAnswer(0);
        }
        if (Input.GetButtonDown("P1_B2") || Input.GetKeyDown(KeyCode.G))
        {
            CheckAnswer(1);
        }
        if (Input.GetButtonDown("P1_B3") || Input.GetKeyDown(KeyCode.H))
        {
            CheckAnswer(2);
        }
    }

    private void CheckAnswer(int index)
    {
        if (!awaitingAnswer)
        {
            return;
        }
        
        // Check if game is over
        if (calculManager != null)
        {
            var gm = FindObjectOfType<GameManager>();
            if (gm != null && gm.Lives <= 0)
            {
                return;
            }
        }
        
        if (calculManager == null)
        {
            calculManager = FindObjectOfType<MiniGame_CalculManager>();
            if (calculManager == null)
            {
                return;
            }
        }

        bool correct = (index == currentCalculation.CorrectAnswerIndex);
        
        if (successImage != null) successImage.enabled = correct;
        if (failImage != null) failImage.enabled = !correct;

        calculManager.OnAnswerSelected(index, correct);

        // Advance flow: on correct, immediately next calculation; on wrong, next generated by manager after life update
        if (correct)
        {
            Invoke("Advance", 0.6f); // brief feedback pause
        }
        else
        {
            Invoke("Advance", 0.6f);
        }
    }

    private void Advance()
    {
        if (this == null || calculManager == null)
        {
            return;
        }

        if (successImage != null) successImage.enabled = false;
        if (failImage != null) failImage.enabled = false;
        calculManager.GenerateNewCalculation();
        awaitingAnswer = true;
    }

    void OnDestroy()
    {
        CancelInvoke();
    }

}
